User tinyproxy
Group tinyproxy
Port 3128
Listen 0.0.0.0
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 50
Allow 10.8.0.0/24
Allow 127.0.0.1
ViaProxyName "pfa-proxy"
ConnectPort 443
ConnectPort 563
ConnectPort 80
